# Generated by Django 5.1.3 on 2025-05-15 19:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatsession_doctor_chatsession_doctor_confirmed_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='type',
            field=models.CharField(choices=[('ai', 'AI'), ('doctor', 'Врач')], default='ai', max_length=10),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_chats', to=settings.AUTH_USER_MODEL),
        ),
    ]
