# Generated by Django 5.1.3 on 2025-06-21 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_chatsession_doctor_alter_chatsession_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='is_survey_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='patient_age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='patient_gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='patient_symptoms',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='survey_step',
            field=models.IntegerField(default=0),
        ),
    ]
