# Generated by Django 5.1.3 on 2025-05-15 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        ('chat', '0003_chatsession_type_alter_chatsession_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='chat_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.chatsession'),
        ),
    ]
