# Generated by Django 5.1.3 on 2025-05-18 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_appointment_chat_session_doctorschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='schedule_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='app.doctorschedule'),
        ),
    ]
