# Generated by Django 5.1.3 on 2025-05-01 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_groups_user_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='achievements',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='consultation_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='education',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='experience_years',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='office_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='specialization',
            field=models.CharField(blank=True, choices=[('therapist', 'Терапевт'), ('neurologist', 'Невролог'), ('cardiologist', 'Кардиолог'), ('surgeon', 'Хирург'), ('pediatrician', 'Педиатр'), ('ophthalmologist', 'Офтальмолог'), ('dentist', 'Стоматолог'), ('psychiatrist', 'Психиатр'), ('dermatologist', 'Дерматолог'), ('other', 'Другое')], max_length=20, null=True),
        ),
    ]
