# Generated by Django 5.1.3 on 2025-05-01 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_achievements_user_bio_user_consultation_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='bio',
            new_name='biography',
        ),
    ]
