# Generated by Django 5.1.3 on 2025-05-01 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_bio_user_biography'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='user',
            name='achievements',
            field=models.TextField(blank=True, verbose_name='Достижения'),
        ),
        migrations.AlterField(
            model_name='user',
            name='biography',
            field=models.TextField(blank=True, verbose_name='О себе'),
        ),
        migrations.AlterField(
            model_name='user',
            name='consultation_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Стоимость консультации'),
        ),
        migrations.AlterField(
            model_name='user',
            name='education',
            field=models.TextField(blank=True, verbose_name='Образование'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='experience_years',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Опыт работы (лет)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=255, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='user',
            name='office_address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Адрес кабинета'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('patient', 'Пациент'), ('doctor', 'Врач')], default='patient', max_length=10, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='user',
            name='specialization',
            field=models.CharField(blank=True, choices=[('therapist', 'Терапевт'), ('neurologist', 'Невролог'), ('cardiologist', 'Кардиолог'), ('surgeon', 'Хирург'), ('pediatrician', 'Педиатр'), ('ophthalmologist', 'Офтальмолог'), ('dentist', 'Стоматолог'), ('psychiatrist', 'Психиатр'), ('dermatologist', 'Дерматолог'), ('other', 'Другое')], max_length=20, null=True, verbose_name='Специализация'),
        ),
    ]
